// LOCALHOST
###
GET http://localhost:8080/contacts

### Create a new contact
POST http://localhost:8080/contacts HTTP/1.1 
content-Type: application/json

{
  "firstName": "Max",
  "lastName": "Payne",
  "email": "maxpayne@example.com",
  "favoriteColor": "yellow",
  "birthday": "1990-01-01"
}

### Update the contact
PUT http://localhost:8080/contacts/64526eeb1c888aff1dcaa9e1 HTTP/1.1 
content-Type: application/json

{
  "firstName": "Van",
  "lastName": "Wilder",
  "email": "vanwilder@example.com",
  "favoriteColor": "green",
  "birthday": "1992-01-01"
}
### Delete the contact
DELETE http://localhost:8080/contacts/645271171c888aff1dcaa9e2



//RENDER
###
GET https://cse-341-iftf.onrender.com/contacts

### Create a new contact
POST https://cse-341-iftf.onrender.com HTTP/1.1 
content-Type: application/json

{
  "firstName": "Max",
  "lastName": "Payne",
  "email": "maxpayne@example.com",
  "favoriteColor": "yellow",
  "birthday": "1990-01-01"
}

### Update the contact
PUT https://cse-341-iftf.onrender.com HTTP/1.1 
content-Type: application/json

{
  "firstName": "Van",
  "lastName": "Wilder",
  "email": "vanwilder@example.com",
  "favoriteColor": "green",
  "birthday": "1992-01-01"
}
### Delete the contact
DELETE https://cse-341-iftf.onrender.com/645271171c888aff1dcaa9e2
